"""Add Teacher details

Revision ID: 4d38fa7acc66
Revises: f11e72585bfd
Create Date: 2026-02-28 02:32:28.577480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d38fa7acc66'
down_revision: Union[str, None] = 'f11e72585bfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('teachers', sa.Column('last_name', sa.String(), nullable=False))
    op.add_column('teachers', sa.Column('email', sa.String(), nullable=True))
    op.add_column('teachers', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'phone')
    op.drop_column('teachers', 'email')
    op.drop_column('teachers', 'last_name')
    op.drop_column('teachers', 'first_name')
    # ### end Alembic commands ###
