"""Add Student details

Revision ID: 7a963667d151
Revises: 4d38fa7acc66
Create Date: 2026-02-28 02:42:15.133225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a963667d151'
down_revision: Union[str, None] = '4d38fa7acc66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('students', sa.Column('email', sa.String(), nullable=True))
    op.add_column('students', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'phone')
    op.drop_column('students', 'email')
    op.drop_column('students', 'date_of_birth')
    # ### end Alembic commands ###
