"""Add subject to classes and avatar_url to teachers

Revision ID: f23a450ea61b
Revises: 7a963667d151
Create Date: 2026-02-28 02:54:45.618746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f23a450ea61b'
down_revision: Union[str, None] = '7a963667d151'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('subject', sa.String(), nullable=True))
    op.add_column('teachers', sa.Column('avatar_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'avatar_url')
    op.drop_column('classes', 'subject')
    # ### end Alembic commands ###
